version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=-Djenkins.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRUMB_ISSUER=true
    restart: no

volumes:
  jenkins_data:
