---
- hosts: servers
  become: yes # This tells Ansible to use 'sudo' for all commands
  vars:
    # These variables will be passed in from the Jenkins pipeline
    docker_hub_repo: "{{ DOCKER_HUB_REPO }}"
    full_image_name: "{{ FULL_IMAGE_NAME }}"
    container_name: "my-app-container-{{ targetenv }}"

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ DOCKER_USER }}"
        password: "{{ DOCKER_PASS }}"

    - name: Deploy the application container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ full_image_name }}"
        pull: yes # Always pull the latest version of the image
        state: started
        restart_policy: always
        ports:
          - "8000:8000"

    - name: Log out from Docker Hub
      community.docker.docker_login:
        state: absent
