# ansible/rolling_update_batch.yml

# STEP 1: Explicitly stop and remove the existing container.
- name: "Ensure old container {{ instance.name }} is removed"
  community.docker.docker_container:
    name: "{{ instance.name }}"
    state: absent

# STEP 2: Add a short pause to allow the OS to fully release the network port.
# This is the key to solving the timing-related "port is already allocated" error.
- name: "Wait for network port to be released"
  ansible.builtin.pause:
    seconds: 3

# STEP 3: Now that the port is guaranteed to be free, create the new container.
- name: "Deploy new container to {{ instance.name }} on port {{ instance.port }}"
  community.docker.docker_container:
    name: "{{ instance.name }}"
    image: "{{ full_image_name }}"
    state: started
    pull: yes
    restart_policy: always
    cleanup: yes
    ports:
      - "{{ instance.port }}:8000"

# STEP 4: Wait for the new container to be healthy.
- name: "Wait for new container {{ instance.name }} to be healthy"
  uri:
    url: "http://localhost:{{ instance.port }}/"
    status_code: 200
  retries: 5
  delay: 10